# Step 1: Modules caching
FROM golang:1.19.2-alpine3.16 AS modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM --platform=$BUILDPLATFORM golang:1.19.2-alpine3.16 AS builder
ARG TARGETOS
ARG TARGETARCH
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN GOFLAGS='-p=1' CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} \
    go build -tags migrate -o /bin/app ./cmd/product

# Step 3: Final
FROM scratch

EXPOSE 5001

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/product/config.yml /
COPY --from=builder /bin/app /app
CMD ["/app"]
